#! /usr/bin/env bash

# Connects nodes in two namespaces by two links with different bandwidth (10mbit and 100mbit)
#
# Optional args:
#   misc/run-twolink-test [node1.conf] [node2.conf]
# If provided, configs are used with a forced AdminListen per node.

set -e

conf1="${1:-}"
conf2="${2:-}"

cleanup() {
  ip link delete veth11 2>/dev/null || true
  ip link delete veth12 2>/dev/null || true
  ip netns delete node1 2>/dev/null || true
  ip netns delete node2 2>/dev/null || true
}

trap cleanup EXIT


make_config() {
  local src="$1"
  local admin="$2"

  if [ -z "$src" ]; then
    printf '{AdminListen: "%s"}\n' "$admin"
    return
  fi

  if [ ! -f "$src" ]; then
    echo "Config not found: $src" >&2
    exit 1
  fi

  hjson-cli -j "$src" \
    | jq --arg admin "$admin" '.AdminListen = $admin' \
    | hjson-cli
}

ip netns add node1
ip netns add node2

ip link add veth11 type veth peer name veth21
ip link set veth11 netns node1 up
ip link set veth21 netns node2 up

ip link add veth12 type veth peer name veth22
ip link set veth12 netns node1 up
ip link set veth22 netns node2 up

ip netns exec node1 tc qdisc add dev veth11 root tbf rate 10mbit burst 8192 latency 1ms
ip netns exec node2 tc qdisc add dev veth21 root tbf rate 10mbit burst 8192 latency 1ms

ip netns exec node1 tc qdisc add dev veth12 root tbf rate 100mbit burst 8192 latency 1ms
ip netns exec node2 tc qdisc add dev veth22 root tbf rate 100mbit burst 8192 latency 1ms

ip netns exec node1 env PPROFLISTEN=localhost:6060 ./yggdrasil \
   -loglevel debug \
   -useconffile <(make_config "$conf1" "unix://node1.sock") \
   &> node1.log &
ip netns exec node2 env PPROFLISTEN=localhost:6060 ./yggdrasil \
   -loglevel debug \
   -useconffile <(make_config "$conf2" "unix://node2.sock") \
   &> node2.log &

echo "Started, to continue you should:"
echo -e "\tsudo kill" $(jobs -p)
wait

cleanup
