name: Yggdrasil

on:
  push:
  pull_request:
  release:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: nix
    steps:
      - uses: actions/checkout@v6
      - run: nix develop .#devShells.x86_64-linux.default --command just lint
      - run: nix develop .#devShells.x86_64-linux.default --command just fmt
      - run: test ! -n "$(git status --porcelain)" || { git status --porcelain; git diff; exit 1; }

  codeql:
    name: Analyse
    runs-on: nix

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Create CodeQL database
        run: nix develop .#devShells.x86_64-linux.default --command codeql database create --language=go codeql-db

      - name: Download CodeQL query packs
        run: nix develop .#devShells.x86_64-linux.default --command codeql pack download codeql/go-queries

      - name: Analyse CodeQL database
        run: nix develop .#devShells.x86_64-linux.default --command codeql database analyze codeql-db codeql/go-queries --format=sarif-latest --output=go.sarif

      - name: Upload SARIF results
        uses: actions/upload-artifact@v3
        with:
          name: codeql-sarif
          path: go.sarif

  build-linux:
    name: Build & Test (Linux)
    needs: [lint]
    runs-on: nix
    steps:
      - uses: actions/checkout@v6

      - name: Build Yggdrasil
        run: nix develop .#devShells.x86_64-linux.default --command go build -v ./...

      - name: Unit tests
        run: nix develop .#devShells.x86_64-linux.default --command go test -v ./...

  build-freebsd:
    strategy:
      fail-fast: false
      matrix:
        goos:
          - freebsd
          - openbsd

    name: Build (Cross ${{ matrix.goos }})
    needs: [lint]
    runs-on: nix
    steps:
      - uses: actions/checkout@v6

      - name: Build Yggdrasil
        run: nix develop .#devShells.x86_64-linux.default --command go build -v ./...
        env:
          GOOS: ${{ matrix.goos }}
          CGO_ENABLED: "0"
