name: Packages

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-vendored-sources:
    name: Vendored Sources
    runs-on: nix
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Vendor dependencies
        run: nix develop .#devShells.x86_64-linux.default --command go mod vendor

      - name: Build archive
        run: |
          NAME="$(nix develop .#devShells.x86_64-linux.default --command just pkgname)"
          VERSION="$(nix develop .#devShells.x86_64-linux.default --command just pkgversion)"
          tar --exclude-vcs --no-xattrs -czf "/tmp/${NAME}-${VERSION}-vendored.tar.gz" .
          mv "/tmp/${NAME}-${VERSION}-vendored.tar.gz" .

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Vendored sources
          path: "*.tar.gz"
          if-no-files-found: error

  build-packages-debian:
    strategy:
      fail-fast: false
      matrix:
        pkgarch: ["amd64", "i386", "mips", "mipsel", "armhf", "armel", "arm64"]

    name: Package (Debian, ${{ matrix.pkgarch }})
    runs-on: nix
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Build package
        run: nix develop .#devShells.x86_64-linux.default --command just build-debian ${{ matrix.pkgarch }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Debian package (${{ matrix.pkgarch }})
          path: "build/*.deb"
          if-no-files-found: error

  build-packages-macos:
    strategy:
      fail-fast: false
      matrix:
        pkgarch: ["amd64", "arm64"]

    name: Package (macOS, ${{ matrix.pkgarch }})
    runs-on: nix
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Build package
        run: nix develop .#devShells.x86_64-linux.default --command just build-macos ${{ matrix.pkgarch }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: macOS package (${{ matrix.pkgarch }})
          path: "build/*.pkg"
          if-no-files-found: error

  build-packages-windows:
    strategy:
      fail-fast: false
      matrix:
        pkgarch: ["x64", "x86"] # todo: arm64 support (requires wix update)

    name: Package (Windows, ${{ matrix.pkgarch }})
    runs-on: nix
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Build package
        run: nix develop .#devShells.x86_64-linux.default --command just build-windows ${{ matrix.pkgarch }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Windows package (${{ matrix.pkgarch }})
          path: "build/*.msi"
          if-no-files-found: error

